project:
  type: website

website:
  title: "Prompting Large Language Models"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/kendallen
        
format:
  html:
    theme: minty
    text: gray
    css: styles.css

execute:
  freeze: auto


