project:
  type: website

website:
  title: "Prompting Large Language Models"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/kendallen
        
format:
  html:
   theme: minty
    css: styles.css

   
execute:
  freeze: auto


