project:
  type: website

website:
  title: "Looking into LLMs"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/kendallen
        
format:
  html:
    theme: cosmo
    css: styles.css

execute:
  freeze: auto


